### ISSUE TITLE
Docusign intitializer

### ISSUE THREAD

**Issue by ilyakatz** [madamkiwi/transaction_tracker#7]
Currently, docusign credentials are in the clear in the git repo. Please create a new set of keys and store those in environmental variables.  Heroku uses https://github.com/laserlemon/figaro so you can use that to keep it simple and secure

https://github.com/madamkiwi/transaction_tracker/blob/master/config/initializers/docusign_rest.rb#L9

**Comment by madamkiwi** [comment]
Done: 1794494157f5df5bd8ba218090e67250d9702257
Thank you!
